// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class AdditiveExpressionNode extends QNode implements QParserTreeConstants {
	public AdditiveExpressionNode() {
		super(JJTADDITIVEEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;
		
		_type = QType.INT;
		
		for (int i=0; i<jjtGetNumChildren(); i++) {
			QType t = getChild(i)._type;
			if (t._kind == QType.Kind.REAL)
				_type = QType.REAL;
			else if (t._kind != QType.Kind.INT)
				throw new CompileException("Expected a number", getChild(i));
		}
	}
}
