// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class AdditiveExpressionNode extends QNode implements QParserTreeConstants {
	public AdditiveExpressionNode() {
		super(JJTADDITIVEEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;
		
		_type = QType.INT;
		
		for (int i=0; i<jjtGetNumChildren(); i++) {
			QType t = getChild(i)._type;
			switch(t._kind) {
			case INT:
				break;
			case REAL:
				_type = QType.REAL;
				break;
			default:
				throw new CompileException("Expected a number", getChild(i));
			}
		}
	}
}