// Stub generated by FactoryMaker

package tree;

import parser.*;

public class ArrayInitializerListNode extends QNode implements QParserTreeConstants {
	public ArrayInitializerListNode() {
		super(JJTARRAYINITIALIZERLIST);
	}

	void initialize() {
	}
}
