// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import compiler.Signature;
import parser.*;

public class ArrayInitializerNode extends QNode implements QParserTreeConstants {
	public int _elementCount;
	
	public ArrayInitializerNode() {
		super(JJTARRAYINITIALIZER);
	}

	void initialize() {
		_elementCount = getChild(0).jjtGetNumChildren();
		
		QType elementType = getChild(0).getChild(0)._type;
		for (int i=1; i<_elementCount; i++) {
			elementType = commonType(elementType, getChild(0).getChild(i)._type);
			if (elementType == null)
				throw new CompileException("Inconsistent types in initializer", getChild(0).getChild(i));
		}
	
		if (elementType._kind == QType.Kind.INTARRAY || elementType._kind == QType.Kind.REALARRAY
				|| elementType._kind == QType.Kind.BOOLEANARRAY || elementType._kind == QType.Kind.PMFARRAY
				|| elementType._kind == QType.Kind.INTERFACEARRAY) {
			for (int rowIndex = 0; rowIndex < _elementCount; rowIndex++) {
				QNode rowNode = getChild(0).getChild(rowIndex);
				if (rowNode.getId() != JJTARRAYINITIALIZER)
					throw new CompileException("Matrix initializer rows must be array literals", rowNode);
			}
		}

		if (elementType._kind == QType.Kind.INT)
			_type = QType.INTARRAY;
		else if (elementType._kind == QType.Kind.REAL)
			_type = QType.REALARRAY;
		else if (elementType._kind == QType.Kind.BOOLEAN)
			_type = QType.BOOLEANARRAY;
		else if (elementType._kind == QType.Kind.PMF)
			_type = new QType(QType.Kind.PMFARRAY, elementType._qualifier);
		else if (elementType._kind == QType.Kind.INTARRAY)
			_type = QType.INTMATRIX;
		else if (elementType._kind == QType.Kind.REALARRAY)
			_type = QType.REALMATRIX;
		else if (elementType._kind == QType.Kind.BOOLEANARRAY)
			_type = QType.BOOLEANMATRIX;
		else if (elementType._kind == QType.Kind.PMFARRAY)
			_type = new QType(QType.Kind.PMFMATRIX, elementType._qualifier);
		else if (elementType._kind == QType.Kind.FUNCTION || elementType._kind == QType.Kind.INTERFACE)
			_type = new QType(QType.Kind.INTERFACEARRAY, (Signature) null);
		else if (elementType._kind == QType.Kind.INTERFACEARRAY)
			_type = new QType(QType.Kind.INTERFACEMATRIX, (Signature) null);
		else
			assert(false);
	}	

	private static QType commonType(QType t1, QType t2) {
		if (t1.isAssignableFrom(t2))
			return t1;
		
		if (t2.isAssignableFrom(t1))
			return t2;
		
		return null;
	}
}
