// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class AttributeExpressionNode extends QNode implements QParserTreeConstants {
	public AttributeExpressionNode() {
		super(JJTATTRIBUTEEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;
		
		QType sourceType = getChild(0)._type;
		switch(getNode(2).getToken(0).kind) {
		case MIN_VALUE:
		case MAX_VALUE:
			if (!sourceType.isAssignableFrom(QType.SIMPLE_PMF))
				throw new CompileException("Expected Pmf{?}", this);
			_type = QType.INT;
			return;
		case LENGTH:
			if (sourceType._kind == QType.Kind.INTARRAY || sourceType._kind == QType.Kind.REALARRAY
					|| sourceType._kind == QType.Kind.BOOLEANARRAY || sourceType._kind == QType.Kind.PMFARRAY
					|| sourceType._kind == QType.Kind.INTMATRIX || sourceType._kind == QType.Kind.REALMATRIX
					|| sourceType._kind == QType.Kind.BOOLEANMATRIX || sourceType._kind == QType.Kind.PMFMATRIX
					|| sourceType._kind == QType.Kind.INTERFACEARRAY || sourceType._kind == QType.Kind.INTERFACEMATRIX) {
				_type = QType.INT;
				return;
			}
			throw new CompileException("Expected array or matrix", this);
			default:
				assert(false);
		}
	}
}
