// Stub generated by FactoryMaker

package tree;

import parser.*;

public class AttributeNode extends QNode implements QParserTreeConstants {
	public AttributeNode() {
		super(JJTATTRIBUTE);
	}

	void initialize() {
	}
}
