// Stub generated by FactoryMaker

package tree;

import compiler.Engine;
import compiler.QType;
import compiler.Signature;
import compiler.Symbol;
import parser.*;

public class CallNode extends QNode implements QParserTreeConstants {
	public CallNode() {
		super(JJTCALL);
	}

	void initialize() {
	}
}
