// Stub generated by FactoryMaker

package tree;

import parser.*;

public class CompoundQualifierNode extends QNode implements QParserTreeConstants {
	public CompoundQualifierNode() {
		super(JJTCOMPOUNDQUALIFIER);
	}

	void initialize() {
	}
}
