// Stub generated by FactoryMaker

package tree;

import parser.*;

public class ExpressionListNode extends QNode implements QParserTreeConstants {
	public ExpressionListNode() {
		super(JJTEXPRESSIONLIST);
	}

	void initialize() {
	}
}
