// Stub generated by FactoryMaker

package tree;

import parser.*;

public class FailStatementNode extends QNode implements QParserTreeConstants {
	public FailStatementNode() {
		super(JJTFAILSTATEMENT);
	}

	void initialize() {
		_isTerminal = true;
	}
}
