// Stub generated by FactoryMaker

package tree;

import compiler.Signature;
import compiler.QType;
import parser.*;

public class ForParametersNode extends QNode implements QParserTreeConstants {
	public ForParametersNode() {
		super(JJTFORPARAMETERS);
	}

	void initialize() {
		Signature signature = new Signature();
		signature._parameterTypes.add(QType.INT);
		signature._parameterNames.add(getToken(1).image);
		
		for (int i=0; i<2; i++)
			if (getChild(i)._type != QType.INT)
				throw new CompileException("Expected an int", getChild(i));
	}
}
