// Stub generated by FactoryMaker

package tree;

import compiler.Signature;
import compiler.QType;
import parser.*;

public class FunctionDeclarationBodyNode extends QNode implements QParserTreeConstants {
	public FunctionDeclarationBodyNode() {
		super(JJTFUNCTIONDECLARATIONBODY);
	}

	void initialize() {
	}
}
