// Stub generated by FactoryMaker

package tree;

import parser.*;

public class IdentifierListNode extends QNode implements QParserTreeConstants {
	public IdentifierListNode() {
		super(JJTIDENTIFIERLIST);
	}

	void initialize() {
	}
}
