// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class LookupNode extends QNode implements QParserTreeConstants {
	public LookupNode() {
		super(JJTLOOKUP);
	}

	void initialize() {
		if (getChild(0)._type != QType.INT)
			throw new CompileException("Expected an int", getChild(0));
		_type = QType.INT;
	}
}
