// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class NegativeExpressionNode extends QNode implements QParserTreeConstants {
	public NegativeExpressionNode() {
		super(JJTNEGATIVEEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;

		_type = getChild(1)._type;

		if (_type._kind != QType.Kind.INT && _type._kind != QType.Kind.REAL)
			throw new CompileException("Expected a number", getChild(0));
	}
}
