// Stub generated by FactoryMaker

package tree;

import parser.*;

public class NegativeNode extends QNode implements QParserTreeConstants {
	public NegativeNode() {
		super(JJTNEGATIVE);
	}

	void initialize() {
	}
}
