// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class NegativeExpressionNode extends QNode implements QParserTreeConstants {
	public NegativeExpressionNode() {
		super(JJTNEGATIVEEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;

		_type = getChild(1)._type;

		switch (_type._kind) {
		case INT:
		case REAL:
			break;
		default:
			throw new CompileException("Expected a number", getChild(0));
		}
	}
}
