// Stub generated by FactoryMaker

package tree;

import compiler.QType;
import parser.*;

public class NotExpressionNode extends QNode implements QParserTreeConstants {
	public NotExpressionNode() {
		super(JJTNOTEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;
		
		_type = QType.BOOLEAN;
		
		if (getChild(1)._type != QType.BOOLEAN) 
			throw new CompileException("Expected a boolean", getChild(1));
	}
}