// Stub generated by FactoryMaker

package tree;

import parser.*;

public class NotNode extends QNode implements QParserTreeConstants {
	public NotNode() {
		super(JJTNOT);
	}

	void initialize() {
	}
}
