// Stub generated by FactoryMaker

package tree;

import compiler.Signature;
import compiler.QType;
import parser.*;

public class ParametersNode extends QNode implements QParserTreeConstants {
	public ParametersNode() {
		super(JJTPARAMETERS);
	}

	void initialize() {
		Signature signature = new Signature();

		for (int i = 0; i < jjtGetNumChildren(); i++) {
			QType parameterType = QType.getType((TypeNode) getChild(i).getChild(0));
			if (parameterType.hasConditionalQualifier())
				throw new CompileException("Function parameters cannot be conditional Pmfs", (QNode) getChild(i).getChild(0));
			signature._parameterTypes.add(parameterType);
			signature._parameterNames.add(getChild(i).getToken(1).image);
			signature._parameterNameTokens.add(getChild(i).getToken(1));
		}
	}
}
