// Stub generated by FactoryMaker

package tree;

import parser.*;

public class ParameterDeclarationNode extends QNode implements QParserTreeConstants {
	public ParameterDeclarationNode() {
		super(JJTPARAMETERDECLARATION);
	}

	void initialize() {
	}
}
