// Stub generated by FactoryMaker

package tree;

import compiler.Signature;
import compiler.QType;
import parser.*;

public class ParametersNode extends QNode implements QParserTreeConstants {
	public ParametersNode() {
		super(JJTPARAMETERS);
	}

	void initialize() {
		Signature signature = new Signature();

		for (int i = 0; i < jjtGetNumChildren(); i++) {
			signature._parameterTypes.add(QType.getType((TypeNode) getChild(i).getChild(0)));
			signature._parameterNames.add(getChild(i).getToken(1).image);
			signature._parameterNameTokens.add(getChild(i).getToken(1));
		}
	}
}
