// Stub generated by FactoryMaker

package tree;

import parser.*;

public class PmfInitializerListNode extends QNode implements QParserTreeConstants {
	public PmfInitializerListNode() {
		super(JJTPMFINITIALIZERLIST);
	}

	void initialize() {
	}
}
