// Stub generated by FactoryMaker

package tree;

import parser.*;

public class PmfInitializerGroupNode extends QNode implements QParserTreeConstants {
	int _dimension;
	
	public PmfInitializerGroupNode() {
		super(JJTPMFINITIALIZERGROUP);
	}

	void initialize() {

		_dimension = ((PmfInitializerElementNode) getChild(0))._dimension;
		
		if (getChild(0) instanceof PmfInitializerGroupNode) {
			for (int i = 1; i < jjtGetNumChildren(); i++) 
				if (_dimension != ((PmfInitializerGroupNode) getChild(i))._dimension) 
					throw new CompileException("Inconsistent sample dimension", getChild(i));
		} else {
			for (int i = 1; i < jjtGetNumChildren(); i++) 
				if (_dimension != ((PmfInitializerElementNode) getChild(i))._dimension) 
					throw new CompileException("Inconsistent sample dimension", getChild(i));
		}
	}
}
