// Stub generated by FactoryMaker

package tree;

import parser.*;

public class PmfInitializerElementNode extends QNode implements QParserTreeConstants {
	int _dimension;
	
	public PmfInitializerElementNode() {
		super(JJTPMFINITIALIZERELEMENT);
	}

	void initialize() {
		int n = jjtGetNumChildren();
        _dimension = n-1;
        
		for (int i=0; i<n-1; i++)
			if (getChild(i)._type._kind != INT)
				throw new CompileException("Expected int", getChild(i));
		
		if (!getChild(n-1)._type.isNumber())
			throw new CompileException("Expected a number", getChild(n-1));
  	}
}
