// Stub generated by FactoryMaker

package tree;

import parser.*;

public class QualifierNode extends QNode implements QParserTreeConstants {
	public QualifierNode() {
		super(JJTQUALIFIER);
	}

	void initialize() {
	}
}
