// Stub generated by FactoryMaker

package tree;

import parser.*;

public class ReturnExpressionElementNode extends QNode implements QParserTreeConstants {
	public ReturnExpressionElementNode() {
		super(JJTRETURNEXPRESSIONELEMENT);
	}

	void initialize() {
	}
}
