// Stub generated by FactoryMaker

package tree;

import parser.*;

public class RootNode extends QNode implements QParserTreeConstants {
	public RootNode() {
		super(JJTROOT);
	}

	void initialize() {
	}
}
