// Stub generated by FactoryMaker

package tree;

import parser.*;

public class SimpleQualifierNode extends QNode implements QParserTreeConstants {
	public SimpleQualifierNode() {
		super(JJTSIMPLEQUALIFIER);
	}

	void initialize() {
	}
}
