// Stub generated by FactoryMaker

package tree;

import java.util.ArrayList;

import parser.*;

public class SkipStatementNode extends QNode implements QParserTreeConstants {
	public SkipStatementNode() {
		super(JJTSKIPSTATEMENT);
	}

	void initialize() {
		_isTerminal = true;
	}
}
