// Stub generated by FactoryMaker

package tree;

import compiler.Engine;
import compiler.QType;
import compiler.Qualifier;
import compiler.Signature;
import compiler.Symbol;
import parser.*;

public class SuffixedExpressionNode extends QNode implements QParserTreeConstants {
	public QType[] _types;

	public SuffixedExpressionNode() {
		super(JJTSUFFIXEDEXPRESSION);
	}

	void initialize() {
		if (children == null)
			return;

		int n = jjtGetNumChildren();
		_types = new QType[n];

		_types[0] = _type = getChild(0)._type;

		for (int i = 1; i < n; i++) {
			QNode child = getChild(i);

			switch (child.getId()) {

			case JJTLOOKUP:
				if (_type._kind == QType.Kind.INTARRAY)
					_type = QType.INT;
				else if (_type._kind == QType.Kind.REALARRAY)
					_type = QType.REAL;
				else if (_type._kind == QType.Kind.PMF) {
					if (_type._qualifier == null  || _type._qualifier._category != Qualifier.Category.SIMPLE
							|| _type._qualifier._simpleRVNames.size() > 1)
						throw new CompileException("Cannot extract a scalar probability from a joint or compound pmf", child);
					_type = QType.REAL;
				} else if (_type._kind == QType.Kind.BOOLEANARRAY)
					_type = QType.BOOLEAN;
				else if (_type._kind == QType.Kind.PMFARRAY)
					_type = new QType(QType.Kind.PMF, _type._qualifier);
				else if (_type._kind == QType.Kind.INTMATRIX)
					_type = QType.INTARRAY;
				else if (_type._kind == QType.Kind.REALMATRIX)
					_type = QType.REALARRAY;
				else if (_type._kind == QType.Kind.BOOLEANMATRIX)
					_type = QType.BOOLEANARRAY;
				else if (_type._kind == QType.Kind.PMFMATRIX)
					_type = new QType(QType.Kind.PMFARRAY, _type._qualifier);
				else if (_type._kind == QType.Kind.INTERFACEARRAY)
					_type = new QType(QType.Kind.INTERFACE, _type._signature);
				else if (_type._kind == QType.Kind.INTERFACEMATRIX)
					_type = new QType(QType.Kind.INTERFACEARRAY, _type._signature);
				else
					throw new CompileException("Type mismatch", this);
				break;

			case JJTQUALIFIER:
				if (_type._kind == QType.Kind.PMF) {
					_type = _type.castTo(new Qualifier((QualifierNode) child));
					if (_type == null)
						throw new CompileException("Invalid Pmf extraction", child);
				} else
					throw new CompileException("Extraction is only supported for a Pmf", child);
				break;

			case JJTCALL: {
				if (_type._kind != QType.Kind.FUNCTION && _type._kind != QType.Kind.INTERFACE)
					throw new CompileException("Syntax error", child);

				Signature signature = _type._signature;

				int m = signature._parameterTypes.size();
				int mm = child.jjtGetNumChildren() == 0 ? 0 : child.getChild(0).jjtGetNumChildren();
				if (m != mm)
					throw new CompileException("Expected " + m + " arguments", child);

				if (m > 0) {
					QNode expressionList = child.getChild(0);
					for (int j = 0; j < m; j++) {
						QType t = signature._parameterTypes.get(j);
						QType tt = expressionList.getChild(j)._type;

						if (!t.isAssignableFrom(tt))
							throw new CompileException("Type mismatch", expressionList.getChild(j));
					}
				}

				if (firstToken.kind == MULTINOMIAL) {
					Token token = child.getChild(0).getChild(1).jjtGetFirstToken();
					if (token.kind != NUMBER || token.image.contains("."))
						throw new CompileException("Second argument must be a literal integer", child);
					int k = Integer.parseInt(token.image);
					_type = new QType(QType.Kind.PMF, new Qualifier(k));
				} else if (firstToken.kind == MULTIVARIATEHYPERGEOMETRIC) {
						Token token = child.getChild(0).getChild(2).jjtGetFirstToken();
						if (token.kind != NUMBER || token.image.contains("."))
							throw new CompileException("Third argument must be a literal integer", child);
						int k = Integer.parseInt(token.image);
						_type = new QType(QType.Kind.PMF, new Qualifier(k));
				} else
					_type = signature._returnType;
			}
			}

			_types[i] = _type;
		}
	}
}
