// Stub generated by FactoryMaker

package tree;

import compiler.Engine;
import compiler.TokenTable;
import compiler.TokenTable.TokenAlreadyDeclaredException;
import parser.*;

public class TokenStatementNode extends QNode implements QParserTreeConstants {
	public TokenStatementNode() {
		super(JJTTOKENSTATEMENT);
	}

	void initialize() {
		boolean isPublic = getToken(0).kind == PUBLIC;
		int k = isPublic ? 1 : 0;
		String token = getToken(k+1).image;
		int value = Integer.parseInt(getToken(k+3).image);
		try {
			Engine._instance._tokenTable.add(isPublic, token, value);
		} catch (TokenAlreadyDeclaredException e) {
			throw new CompileException("Token already declared", getToken(1));
		}
	}
}
