// Stub generated by FactoryMaker

package tree;

import parser.*;

public class TypeNode extends QNode implements QParserTreeConstants {
	public TypeNode() {
		super(JJTTYPE);
	}

	void initialize() {
	}
}
