// Stub generated by FactoryMaker

package tree;

import parser.*;

public class WhileStatementNode extends QNode implements QParserTreeConstants {
	public WhileStatementNode() {
		super(JJTWHILESTATEMENT);
	}

	void initialize() {
		_samplingDepth = getChild(1)._samplingDepth;
		_hasSkipBeforeSampling = getChild(1)._hasSkipBeforeSampling;
		_isTerminal = false;
		_returnValueNodes = getChild(1)._returnValueNodes;
	}
}
